package minimal_v0_9_0

const MAX_VALIDATORS_PER_COMMITTEE = 2048

const SLOTS_PER_EPOCH = 8

const SLOTS_PER_ETH1_VOTING_PERIOD = 16

const SLOTS_PER_HISTORICAL_ROOT = 64

const EPOCHS_PER_HISTORICAL_VECTOR = 64

const EPOCHS_PER_SLASHINGS_VECTOR = 64

const HISTORICAL_ROOTS_LIMIT = 16777216

const VALIDATOR_REGISTRY_LIMIT = 1099511627776

const MAX_PROPOSER_SLASHINGS = 16

const MAX_ATTESTER_SLASHINGS = 1

const MAX_ATTESTATIONS = 128

const MAX_DEPOSITS = 16

const MAX_VOLUNTARY_EXITS = 16

const DEPOSIT_CONTRACT_TREE_DEPTH = 32

const JUSTIFICATION_BITS_LENGTH = 4
